### ISSUE TITLE
Test on non .deb based OS

### ISSUE THREAD

**Issue by DavidLutton** [DavidLutton/DAB-recipes#1]

**Comment by mpbraendli** [comment]
I succeeded compiling odr-dabmux-next on Fedora 23, and I have removed the ka9q-fec dependency. I had to a satisfy to curl based on pkgconfig.
I'll try the other projects.

**Comment by mpbraendli** [comment]
odr-audioenc and odr-padenc work. Needed some more library changes.

**Comment by mpbraendli** [comment]
Installing odr-dabmod-next properly. installs fftw and uhd.

**Comment by mpbraendli** [comment]
dablin and etisnoop fail because of faad. I've opened an issue https://github.com/gnuradio/gr-recipes/issues/61

**Comment by DavidLutton** [comment]
@mpbraendli can you enable Travis CI on this repo please 

Most of Opendigitalradio works in Travis CI moved back to this repo, build logs [DavidLutton/DAB-recipes - Travis CI](https://travis-ci.org/DavidLutton/DAB-recipes)

**Comment by mpbraendli** [comment]
Yeah sure!
https://travis-ci.org/Opendigitalradio/DAB-recipes

**Comment by DavidLutton** [comment]
@mpbraendli with gr-recipes#61 faad fix, does dablin and etisnoop now build?

**Comment by mpbraendli** [comment]
dablin clones and fails because cmake didn't find sdl2.

etisnoop compiles fine.

Tested on a Fedora Core 23 I need to upgrade to 25 now.

**Comment by mpbraendli** [comment]
This issue is a bit dated, does it still make sense keeping it open? We probably have to test again (ideally in an automated way) with newer dists.
@DavidLutton Can I close this?
