### ISSUE TITLE
odr-audioenc recipe fails to detect libmagicwand

### ISSUE THREAD

**Issue by rashrf** [DavidLutton/DAB-recipes#2]
This was done using the Debian Jessie minimal image released in September. I don't have the fine detail to hand unfortunately.

pi@raspberrypi:~ $ list="odr-audioenc odr-padenc fdk-aac ka9q-fec"
pi@raspberrypi:~ $ pybombs install $list
PyBOMBS - INFO - PyBOMBS Version 2.2.0
PyBOMBS.DepManager - ERROR - Package does not exist: libmagickwand (declared as dependency for package odr-audioenc)

However:

pi@raspberrypi:~ $ sudo apt-get install libmagickwand-dev
Reading package lists... Done
Building dependency tree  
Reading state information... Done
libmagickwand-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

I haven't really looked into it further. I was able to compile odr-audioenc in the usual way, so it looks like the recipe fails to detect it for some reason.

**Comment by DavidLutton** [comment]
Just worked in a fresh prefix on PC with Ubuntu 16.04.1.

Try: 
`pybombs recipes update`
`list="odr-audioenc odr-padenc fdk-aac ka9q-fec"`
`pybombs -vv install $list 2>&1 | tee -a build.log`  
Create a gist with the log

**Comment by DavidLutton** [comment]
On a VM installed debian-8.6.0-amd64-netinst and selecting only 'minimal system utilities':
apt install python3-pip python3-venv 
python3 -m venv pybombs
. pybombs/bin/activate
pip install pybombs
pybombs recipes add gr-recipes git+https://github.com/gnuradio/gr-recipes.git
pybombs recipes add gr-etcetera git+https://github.com/gnuradio/gr-etcetera.git
pybombs recipes add dab-recipes git+https://github.com/Opendigitalradio/DAB-recipes.git
pybombs prefix init ~/prefix/ -a dab
list="odr-audioenc odr-padenc"  # Let pybombs resolve dependences
pybombs install $list

. ~/prefix/setup_env.sh
odr-padenc
odr-audioenc 

Built without issue, I consider issue closed without further information.
